# Use root/example as user/password credentials
version: '3.8'

services:
  test_forum_db:
    image: mysql
    container_name: test_forum_db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $DB_PORT:$DB_PORT_DOCKER
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: $DB_NAME
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
